SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `nexusdev` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `nexusdev`;



-- Users Table And Related Procedures --
CREATE TABLE IF NOT EXISTS `users`
(
  -- Keys --
  `uid` int(11) NOT NULL AUTO_INCREMENT,  -- Primary Key --
  
  -- Credentials --
  `email_address` varchar(320) NOT NULL,
  `password` text NOT NULL,

  -- Profile Info --
  `fname` varchar(32) NOT NULL,
  `mname` varchar(32) DEFAULT NULL,
  `lname` varchar(32) NOT NULL,
  `bio` varchar(1024) NOT NULL DEFAULT '',
  `pfp` varchar(255) DEFAULT NULL COMMENT 'Path to profile picture',

  -- Permissions --
  `freelancer` tinyint(1) NOT NULL DEFAULT 0,
  `owner_privileges` tinyint(1) NOT NULL DEFAULT 0,
  
  -- Constraints --
  Primary Key (uid)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` (`email_address`, `password`, `fname`, `mname`, `lname`, `bio`, `pfp`, `freelancer`, `owner_privileges`) VALUES
('simo@nexusdev.hu', '$2b$10$QpYfB/UgxrWgLXe6ROGj9.fPw3H1r8soB2VWq/kPOtX2NqZKs.vxe', 'Simó', '', 'Zsolt', 'Experienced Web Application Developer and Backend Engineer with several years of expertise in designing, building, and maintaining scalable web applications and server-side solutions.', '1772533736332-simo.jpeg', 0, 1),
('miki@nexusdev.hu', '$2b$10$V3PRGS1zM/UBPDhQIsqY..9kNl5yM7ZnxVKyzGfv7PFTG74XmO4R2', 'Farkas', '', 'Miklós', 'Creative Designer specializing in crafting intuitive, user-friendly interfaces that enhance user experience and engagement through thoughtful and innovative design.', '1772533736332-miki.jpeg', 0, 1),
('vendel@nexusdev.hu', '$2b$10$ZiOg81YjMvtKHjJnSzauFuKHnb7IWQALP.rC91wg4ZQE.ILKlUbMu', 'Medgyes', '', 'Vendel', 'Expert in Databases and Server-Side Solutions, specializing in designing, optimizing, and maintaining robust backend systems and scalable data architectures.', '1772533736332-vendel.jpeg', 0, 1),
('peter@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Péter', '', 'Szabó', 'Experienced Project Manager with 7 years of expertise in coordinating complex software development projects, team leadership, and stakeholder communication. Specialized in Agile methodologies and resource optimization.', 'default.png', 0, 0),
('anna@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Anna', '', 'Kiss', 'Talented UI/UX Designer with a passion for creating beautiful and functional user interfaces. Skilled in user research, wireframing, and design systems with strong experience in both web and mobile platforms.', 'default.png', 0, 0),
('robert@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Róbert', 'János', 'Kovács', 'Strategic Marketing Professional focused on digital transformation and brand development. Expertise in marketing analytics, campaign management, and market research with proven track record of increasing customer engagement.', 'default.png', 0, 0),
('maria@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Mária', '', 'Nagy', 'Customer Service Manager with exceptional communication skills and dedication to client satisfaction. 5 years of experience in handling complex customer inquiries, resolving conflicts diplomatically, and improving service quality.', 'default.png', 0, 0),
('david@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Dávid', '', 'Tóth', 'Professional Trainer and Education Specialist dedicated to developing workforce capabilities. Expert in curriculum design, corporate training delivery, and skill development programs with proven effectiveness in knowledge transfer.', 'default.png', 0, 0),
('katalin@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Katalin', '', 'Molnár', 'Product Manager with deep knowledge of market trends and user needs. Specialized in product roadmap development, feature prioritization, and cross-functional collaboration to drive product success and innovation.', 'default.png', 0, 0),
('david2@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Dániel', '', 'Horváth', 'Quality Assurance Engineer dedicated to ensuring software excellence. Experienced in test automation, manual testing, bug tracking, and quality metrics. Strong attention to detail and commitment to delivering bug-free products.', 'default.png', 0, 0),
('zsofia@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Zsófia', '', 'Ferenc', 'Graphic Designer with a creative eye for visual storytelling. Proficient in branding, illustration, and multimedia design. Passionate about creating impactful visual content that resonates with target audiences.', 'default.png', 0, 0),
('viktor@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Viktor', '', 'Lukács', 'Content Writer and Copywriter specializing in engaging, SEO-optimized content creation. Experienced in blog writing, technical documentation, and marketing materials with strong research and editing capabilities.', 'default.png', 0, 0),
('gergo@ngmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Gergő', '', 'Szilágyi', 'Data Analyst with strong statistical background and proficiency in data visualization tools. Skilled in translating complex data into actionable business insights, predictive analytics, and performance reporting.', 'default.png', 0, 0),
('balazs@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Balázs', '', 'Vincze', 'Full Stack Developer with expertise spanning frontend and backend technologies. 8 years of professional experience in designing scalable web applications, system architecture, and solving complex technical challenges. Available for contract work.', 'default.png', 1, 0),
('laszlo@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'László', '', 'Bodnár', 'Mobile Application Developer specializing in iOS and Android development using React Native and Flutter. Proven track record of delivering high-performance, user-friendly mobile apps with millions of downloads.', 'default.png', 1, 0),
('anita@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Anita', '', 'Dróth', 'AI and Machine Learning Engineer with advanced knowledge in natural language processing, computer vision, and predictive modeling. Experienced in implementing cutting-edge ML solutions for enterprise clients.', 'default.png', 1, 0),
('istvan@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'István', 'Pál', 'Valent', 'Cloud Solutions Architect specializing in AWS and Azure infrastructure design. Expert in designing scalable, secure, and cost-efficient cloud solutions for enterprises undergoing digital transformation.', 'default.png', 1, 0),
('eva@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Éva', '', 'Sándor', 'DevOps Engineer with strong background in containerization, orchestration, and CI/CD pipeline management. Experienced in leading infrastructure modernization projects and ensuring system reliability at scale.', 'default.png', 1, 0),
('miklos@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Miklós', '', 'Kővári', 'Cybersecurity Specialist with expertise in penetration testing, vulnerability assessment, and security architecture. Committed to protecting systems and data from evolving cyber threats through proactive security measures.', 'default.png', 1, 0),
('jozsef@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'József', '', 'Páll', 'Blockchain Developer specializing in smart contract development and cryptocurrency protocols. Experienced with Solidity, Web3.js, and decentralized finance applications. Passionate about blockchain innovation.', 'default.png', 1, 0),
('rita@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Rita', '', 'Kálmán', 'Game Developer with creative passion for interactive entertainment. Specialized in game design, graphics programming, and physics engines using Unity and Unreal Engine. Portfolio includes successful indie game releases.', 'default.png', 1, 0),
('tamas@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Tamás', '', 'Faragó', 'Data Scientist and Analytics Expert with advanced statistical knowledge and machine learning proficiency. Specialized in building predictive models, data mining, and providing strategic insights from complex datasets.', 'default.png', 1, 0),
('noemi@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Noémi', '', 'Sulyok', 'Freelance UI/UX Designer and Front-end Developer with artistic sensibility and technical prowess. Specializes in creating beautiful, responsive interfaces with exceptional user experiences. Portfolio showcases award-winning designs.', 'default.png', 1, 0),
('marton@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Márton', '', 'Gál', 'Business Development Manager with expertise in market expansion and partnership development. Strong network within the tech industry with track record of identifying new business opportunities and driving revenue growth.', 'default.png', 0, 0),
('petra@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Petra', '', 'Szöllősi', 'Technical Writer specializing in software documentation and user guides. Excellent ability to translate complex technical concepts into clear, accessible documentation for both technical and non-technical audiences.', 'default.png', 0, 0),
('sándor@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Sándor', '', 'Kiss', 'System Administrator with comprehensive knowledge of network infrastructure, server management, and IT security. Experienced in managing both on-premises and cloud-based systems with high availability requirements.', 'default.png', 0, 0),
('bernadett@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Bernadett', '', 'Rácz', 'Copywriter and Content Marketing Specialist focused on creating compelling brand narratives. Skilled in writing marketing materials, website copy, and email campaigns that drive conversions and customer engagement.', 'default.png', 0, 0),
('janos@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'János', '', 'Varga', 'IT Project Coordinator with experience in managing IT infrastructure projects and technology implementations. Focus on timeline management, budget control, and stakeholder communication throughout project lifecycle.', 'default.png', 0, 0),
('orsolya@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Orsolya', '', 'Benedek', 'Social Media Manager with strong content strategy and community management skills. Experienced in building engaged audiences, creating viral content, and managing brand reputation across multiple social platforms.', 'default.png', 0, 0),
('lilla@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Lilla', '', 'Szatmár', 'SEO Specialist and Digital Marketing Expert focused on organic search optimization and content strategy. Proven ability to improve search rankings, increase organic traffic, and implement comprehensive digital marketing campaigns.', 'default.png', 0, 0),
('gyorgy@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'György', '', 'Soós', 'Financial Analyst with expertise in financial modeling, budget forecasting, and investment analysis. Strong proficiency in financial reporting tools and ability to provide strategic financial insights for business decisions.', 'default.png', 0, 0),
('zita@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Zita', '', 'Bodnár', 'HR Specialist focused on recruitment, employee development, and organizational culture building. Experienced in implementing HR policies, conducting interviews, and creating positive workplace environments that attract talent.', 'default.png', 0, 0),
('arpad@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Árpád', '', 'Szűcs', 'API and Backend Integration Specialist with deep expertise in REST API design, microservices architecture, and system integration. Experienced in building robust, scalable backend systems and API documentation.', 'default.png', 1, 0),
('katalin2@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Katalin', '', 'Balog', 'E-commerce Specialist with expertise in building and optimizing online stores, payment gateway integration, and conversion rate optimization. Track record of increasing online sales and improving customer experience.', 'default.png', 1, 0),
('krisztian@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Krisztián', '', 'Németh', 'React Native Specialist focused on cross-platform mobile app development with code reusability and performance optimization. Experienced in building feature-rich applications for iOS and Android platforms.', 'default.png', 1, 0),
('agnes@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Ágnes', '', 'Jakab', 'WordPress Developer and Plugin Specialist with extensive experience in customizing and extending WordPress functionality. Skilled in theme development, plugin creation, and WordPress optimization for performance and SEO.', 'default.png', 1, 0),
('sandor2@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Sándor', '', 'Csillag', 'IoT Solutions Developer with expertise in embedded systems, sensor integration, and Internet of Things architecture. Experienced in developing connected devices and IoT platforms for smart home and industrial applications.', 'default.png', 1, 0),
('margit@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Margit', '', 'Takács', 'Vue.js Specialist with deep knowledge of progressive web applications and modern frontend frameworks. Expert in building reactive, high-performance user interfaces with excellent developer experience.', 'default.png', 1, 0),
('laszlo2@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'László', '', 'Gál', 'Python Web Developer specializing in Django and Flask frameworks for building scalable web applications. Experienced in API development, database design, and deployment of Python-based solutions.', 'default.png', 1, 0),
('eszter@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Eszter', '', 'Mórvái', 'UX Research Specialist focused on understanding user needs through research methodologies, usability testing, and user feedback analysis. Skilled in translating research insights into design recommendations.', 'default.png', 1, 0),
('mihaly@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Mihály', '', 'Bognár', 'Java Enterprise Developer with extensive experience in enterprise application development, J2EE, and Spring Framework. Specialized in building large-scale, high-availability systems for Fortune 500 companies.', 'default.png', 1, 0),
('agnes2@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Ágnes', '', 'Biró', 'Technical SEO Specialist with expertise in search engine optimization, schema markup, and technical website audits. Focused on improving technical performance and ensuring websites are fully optimized for search engines.', 'default.png', 1, 0),
('tamas.v@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Tamás', '', 'Varga', 'Development Manager with expertise in team leadership, sprint management, and agile transformation. Strong background in mentoring developers and optimizing development processes for maximum productivity.', 'default.png', 0, 0),
('eva.h@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Éva', '', 'Horváth', 'Product Designer focused on creating user-centered product designs with emphasis on usability and aesthetics. Experienced in design systems, prototyping, and cross-functional collaboration with development teams.', 'default.png', 0, 0),
('peter.m@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Péter', '', 'Molnár', 'Business Analyst specializing in requirements gathering, process optimization, and solution design. Skilled in stakeholder management and translating business needs into technical specifications.', 'default.png', 0, 0),
('klaudia@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Klaudia', '', 'Szabó', 'Compliance Officer with deep knowledge of data protection regulations, GDPR compliance, and organizational policy implementation. Experienced in risk assessment and regulatory audit management.', 'default.png', 0, 0),
('mark@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Márk', '', 'Kővári', 'Technical Support Manager with strong problem-solving skills and customer focus. Experienced in building support teams, incident management, and creating knowledge bases for technical support.', 'default.png', 0, 0),
('diana@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Diana', '', 'Sándor', 'Communications Specialist focused on internal and external communication strategies. Skilled in crisis communication, stakeholder engagement, and building organizational messaging frameworks.', 'default.png', 0, 0),
('robert.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Róbert', '', 'Kiss', 'Quality Assurance Manager overseeing quality standards and testing strategies. Experienced in building QA teams, test automation frameworks, and implementing continuous quality improvement processes.', 'default.png', 0, 0),
('szandra@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Szandra', '', 'Filip', 'Business Intelligence Analyst with expertise in data warehousing, business analytics, and reporting dashboards. Skilled in translating data into actionable business insights and KPI tracking.', 'default.png', 0, 0),
('florian@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Flórián', '', 'Papp', 'Strategic Planning Manager focused on long-term business strategy and competitive positioning. Experienced in market analysis, strategic planning, and business development initiatives.', 'default.png', 0, 0),
('beatrice@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Beatrix', '', 'Lang', 'Brand Manager with expertise in brand development, market positioning, and brand identity management. Skilled in brand strategy, consumer insights, and brand communication campaigns.', 'default.png', 0, 0),
('stefan@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Stef', '', 'Baláž', 'Operations Manager specialized in process optimization, supply chain management, and operational excellence. Experienced in resource planning and efficiency improvements.', 'default.png', 0, 0),
('rozalia@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Rozália', '', 'Németh', 'Legal Compliance Manager with expertise in contract management, legal compliance, and regulatory affairs. Experienced in risk mitigation and legal strategy development.', 'default.png', 0, 0),
('david.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Dávid', '', 'Kocsis', 'Procurement Specialist focused on vendor management, cost optimization, and supply chain efficiency. Skilled in negotiation and contract administration.', 'default.png', 0, 0),
('nina@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Nina', '', 'Gulyás', 'Event Manager with expertise in organizing corporate events, conferences, and team-building activities. Skilled in project coordination and vendor management.', 'default.png', 0, 0),
('viktor.s@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Viktor', '', 'Sólyom', 'Risk Management Specialist focused on enterprise risk assessment and mitigation strategies. Experienced in business continuity planning and crisis management.', 'default.png', 0, 0),
('justyna@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Justyna', '', 'Park', 'Training Coordinator specialized in employee development programs and certification management. Skilled in curriculum design and learning management systems.', 'default.png', 0, 0),
('robert.s@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Róbert', '', 'Strack', 'Customer Relations Manager focused on account management and customer retention. Experienced in building long-term customer relationships and handling escalations.', 'default.png', 0, 0),
('anna.z@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Anna', '', 'Zsigmond', 'Partnership Development Manager specializing in strategic partnerships and business collaborations. Skilled in negotiation and mutual benefit identification.', 'default.png', 0, 0),
('mark.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Márk', '', 'Kocsis', 'Localization Manager with expertise in multilingual content management and cultural adaptation. Experienced in managing translation projects and ensuring cultural relevance.', 'default.png', 0, 0),
('barbara@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Barbara', '', 'Lőrincz', 'Accessibility Specialist focused on WCAG compliance and inclusive design. Skilled in accessibility audits and assistive technology implementation.', 'default.png', 0, 0),
('andras@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'András', '', 'Péntes', 'Sustainability Manager specialized in green initiatives and corporate social responsibility. Experienced in environmental compliance and sustainability reporting.', 'default.png', 0, 0),
('gizella@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Gizella', '', 'Sarka', 'Technology Innovation Manager focused on emerging technologies and digital transformation. Skilled in evaluating new tech solutions and implementation planning.', 'default.png', 0, 0),
('piotr@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Piotr', '', 'Kovács', 'Database Solutions Architect specializing in database optimization and data governance. Experienced in performance tuning and database migration projects.', 'default.png', 0, 0),
('alexandra@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Alexandra', '', 'Vincze', 'API Framework Developer with expertise in RESTful architecture and microservices integration. Skilled in building scalable API infrastructures and documentation.', 'default.png', 0, 0),
('ernst@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Ernst', '', 'Szarka', 'Testing Infrastructure Engineer specializing in test automation and CI/CD pipeline optimization. Experienced in building robust testing frameworks.', 'default.png', 0, 0),
('simona@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Simona', '', 'Papp', 'Documentation Manager focused on technical writing and knowledge management. Skilled in creating comprehensive technical documentation and style guides.', 'default.png', 0, 0),
('jozef@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Józef', '', 'Dudás', 'Systems Integration Specialist with expertise in enterprise system integration and middleware solutions. Experienced in complex system implementations.', 'default.png', 0, 0),
('olga@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Olga', '', 'Takács', 'Mobile User Experience Designer focused on creating intuitive mobile interfaces. Skilled in mobile usability testing and responsive design principles.', 'default.png', 0, 0),
('kristof@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Kristóf', '', 'Szücs', 'Web Performance Engineer specializing in performance optimization and load testing. Experienced in reducing page load times and improving user experience.', 'default.png', 0, 0),
('carolina@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Karolina', '', 'Bár', 'Security Audit Manager with expertise in vulnerability assessment and penetration testing. Skilled in security compliance audits and risk reporting.', 'default.png', 0, 0),
('bence@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Bence', '', 'Magyar', 'Monitoring and Alerting Systems Developer experienced in system health monitoring. Skilled in implementing alerting systems and performance dashboards.', 'default.png', 0, 0),
('emilia@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Emília', '', 'Géza', 'Health and Safety Coordinator focused on workplace safety protocols and compliance. Experienced in safety training and incident prevention.', 'default.png', 0, 0),
('matyas@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Mátyás', '', 'Sándor', 'Employee Wellness Program Manager specializing in mental health support and employee engagement. Skilled in designing effective wellness initiatives.', 'default.png', 0, 0),
('fanni@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Fanni', '', 'Berecz', 'Innovation Lab Manager focused on fostering creative thinking and prototyping new solutions. Experienced in managing innovation projects and teams.', 'default.png', 0, 0),
('norbert@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Norbert', '', 'Kecskeméty', 'Version Control Administrator managing code repositories and developer workflows. Skilled in Git workflows and branching strategies.', 'default.png', 0, 0),
('rebeka@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Rebeka', '', 'Fekete', 'Data Privacy Officer specializing in personal data protection and privacy compliance. Experienced in data protection impact assessments.', 'default.png', 0, 0),
('istvan.z@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'István', '', 'Zachar', 'Configuration Management Specialist managing application configurations and deployment settings. Skilled in environment management and version control.', 'default.png', 0, 0),
('melinda@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Melinda', '', 'Turóczi', 'Change Management Coordinator focused on organizational change processes and adoption. Experienced in change communication and resistance management.', 'default.png', 0, 0),
('sandor.m@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Sándor', '', 'Módos', 'Disaster Recovery Planner specializing in business continuity and recovery strategies. Skilled in disaster recovery testing and plan documentation.', 'default.png', 0, 0),
('konstanca@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Konstanca', '', 'Ionida', 'Vendor Management Specialist focused on third-party vendor relationships and contracts. Experienced in SLA management and vendor performance evaluation.', 'default.png', 0, 0),
('attila@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Attila', '', 'Tóbiás', 'License Compliance Manager overseeing software licensing and compliance. Skilled in license audits and cost optimization strategies.', 'default.png', 0, 0),
('judit@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Judit', '', 'Szakáll', 'Incident Management Coordinator managing critical incidents and escalations. Experienced in incident response and root cause analysis.', 'default.png', 0, 0),
('gyula@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Gyula', '', 'Schäffer', 'Capacity Planning Manager specializing in infrastructure capacity and resource planning. Skilled in predictive analytics and growth planning.', 'default.png', 0, 0),
('eva.t@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Éva', '', 'Tóth', 'Green IT Specialist focused on energy-efficient technology and sustainable operations. Experienced in reducing IT carbon footprint.', 'default.png', 0, 0),
('balint@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Bálint', '', 'Visontai', 'User Adoption Manager supporting end-user adoption of new technologies. Skilled in training delivery and user support strategies.', 'default.png', 0, 0),
('sara@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Sára', '', 'Farkas', 'Metrics and Analytics Manager focused on business metrics and KPI analysis. Experienced in data-driven decision making.', 'default.png', 0, 0),
('lászló.s@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'László', '', 'Stabil', 'Architecture Review Manager specializing in technical architecture assessments. Skilled in system design evaluation and best practices.', 'default.png', 0, 0),
('zsofia.m@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Zsófia', '', 'Malinovszky', 'Requirements Management Specialist focused on requirement collection and stakeholder analysis. Skilled in requirements documentation and traceability.', 'default.png', 0, 0),
('gergely@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Gergely', '', 'Hámori', 'Release Manager coordinating software releases and deployment schedules. Experienced in release planning and rollback procedures.', 'default.png', 0, 0),
('magda@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Magda', '', 'Szarka', 'Knowledge Management Specialist developing knowledge bases and documentation systems. Skilled in creating searchable knowledge repositories.', 'default.png', 0, 0),
('kalman@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Kálmán', '', 'Buzás', 'Feedback Collection Manager focused on customer feedback systems and survey management. Experienced in feedback analysis and action planning.', 'default.png', 0, 0),
('vera@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Vera', '', 'Szilvia', 'Competitive Analysis Specialist researching market trends and competitor strategies. Skilled in SWOT analysis and market positioning.', 'default.png', 0, 0),
('akos@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Ákos', '', 'Pál', 'Platform Migration Specialist experienced in migrating systems to new platforms. Skilled in minimizing downtime and data integrity.', 'default.png', 0, 0),
('agneszka@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Agnieszka', '', 'Tóth', 'Service Catalog Manager maintaining IT service catalogs and offering management. Experienced in SLA definition and service documentation.', 'default.png', 0, 0),
('laszlo.b@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'László', '', 'Bodnár', 'Network Security Manager specializing in network protection and threat detection. Skilled in firewall management and network monitoring.', 'default.png', 0, 0),
('anna.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Anna', '', 'Kálmán', 'Virtualization Administrator managing virtual infrastructure and resource optimization. Experienced in hypervisor management and VM administration.', 'default.png', 0, 0),
('zsolt@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Zsolt', '', 'Benedek', 'Integration Platform Developer specializing in enterprise integration platforms. Skilled in workflow automation and system connectivity.', 'default.png', 0, 0),
('orsi@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Orsolya', '', 'Goda', 'Application Performance Monitoring Manager focused on APM tools and performance tracking. Experienced in performance troubleshooting and optimization.', 'default.png', 0, 0),
('mihaly.n@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Mihály', '', 'Nagy', 'Disaster Recovery Technician implementing backup and recovery solutions. Skilled in backup automation and recovery testing.', 'default.png', 0, 0),
('eszter.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Eszter', '', 'Kovácsmáté', 'Storage Administrator managing storage infrastructure and data tiering. Experienced in SAN management and storage optimization.', 'default.png', 0, 0),
('robert.b@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Róbert', '', 'Baláž', 'Identity and Access Management Specialist managing IAM systems and user provisioning. Skilled in authentication and authorization frameworks.', 'default.png', 0, 0),
('barbara.s@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Barbara', '', 'Sándor', 'Helpdesk Manager overseeing support operations and ticket management. Experienced in improving support metrics and team productivity.', 'default.png', 0, 0),
('gabor.f@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Gábor', '', 'Fekete', 'Python Expert with 12 years of experience in backend development and data science. Specialized in Django, FastAPI, and machine learning implementations. Proven track record with startups and enterprises.', 'default.png', 1, 0),
('dora.s@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Dóra', '', 'Szilágyi', 'Frontend Developer specializing in React and Vue.js with 10 years of industry experience. Expertise in responsive design and modern web standards. Passionate about user experience optimization.', 'default.png', 1, 0),
('gabor.j@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Gábor', '', 'Juhász', 'C# and .NET Expert with extensive enterprise application development experience. Specialized in ASP.NET Core and cloud solutions. Strong track record with Fortune 500 clients.', 'default.png', 1, 0),
('zsuzsanna@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Zsuzsanna', '', 'Gál', 'iOS Developer with 9 years of Swift and Objective-C experience. Specialized in complex app architectures and performance optimization. Portfolio includes top-rated AppStore applications.', 'default.png', 1, 0),
('peterh@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Péter', '', 'Horváth', 'Android Developer specializing in Kotlin and Java platforms. Experienced in building scalable mobile solutions with 11 years in mobile development. Strong background in app performance and security.', 'default.png', 1, 0),
('krisztina.n@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Krisztina', '', 'Nagy', 'UI/UX Designer with strong focus on accessibility and inclusive design principles. 8 years of experience creating beautiful, functional interfaces. Award-winning portfolio in web and mobile design.', 'default.png', 1, 0),
('zoltan.v@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Zoltán', '', 'Varga', 'DevOps Engineer with expertise in Kubernetes, Docker, and AWS infrastructure. 10 years of experience in building scalable deployment pipelines. Specialized in high-availability systems.', 'default.png', 1, 0),
('martina@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Martina', '', 'Kováčová', 'QA Automation Engineer with expertise in Selenium and test framework development. 9 years of experience ensuring software quality through comprehensive automation. Specialized in CI/CD integration.', 'default.png', 1, 0),
('janos.j@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'János', '', 'Jánosi', 'WordPress and PHP Specialist with 11 years of web development experience. Strong expertise in custom plugin development and WooCommerce integration. Proven success with e-commerce solutions.', 'default.png', 1, 0),
('anna.l@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Anna', '', 'Lehotai', 'UI Designer specializing in design systems and component libraries. 7 years of experience creating cohesive brand identities through systematic design approaches. Strong Figma and Adobe skills.', 'default.png', 1, 0),
('oliver.v@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Olivier', '', 'Vincent', 'Full Stack Node.js Developer with 10 years of JavaScript ecosystem expertise. Specialized in Express, NestJS, and real-time applications. Strong background in scalable API development.', 'default.png', 1, 0),
('petra.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Petra', '', 'Kácsor', 'Product Manager with SaaS startup experience and 12 years in product development. Expertise in market validation and feature prioritization. Proven track record of successful product launches.', 'default.png', 1, 0),
('mark.l@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Márk', '', 'Lukács', 'Database Administrator specializing in PostgreSQL and MongoDB. 11 years of experience optimizing complex database systems. Expert in scaling and performance tuning.', 'default.png', 1, 0),
('barbara.t@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Barbara', '', 'Tak', 'Business Analyst specializing in enterprise process mapping and requirements analysis. 10 years of experience translating business needs into technical solutions.', 'default.png', 1, 0),
('david.p@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Dávid', '', 'Puskás', 'Cloud Architect with deep AWS expertise and multi-cloud experience. 12 years specializing in enterprise cloud transformations and serverless architectures.', 'default.png', 1, 0),
('eva.n@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Éva', '', 'Nagy', 'UX Researcher with expertise in user interviews and usability testing. 8 years of experience conducting research that drives design decisions. Specialized in quantitative analysis.', 'default.png', 1, 0),
('tamas.b@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Tamás', '', 'Bodnár', 'Security Engineer specializing in application security and penetration testing. 11 years of experience identifying and mitigating security vulnerabilities.', 'default.png', 1, 0),
('szilvia@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Szilvia', '', 'Kiss', 'Content Strategist with expertise in SEO-driven content creation and marketing. 9 years of experience building content that generates organic traffic and engagement.', 'default.png', 1, 0),
('robert.n@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Róbert', '', 'Nagy', 'API Gateway Architect specializing in microservices orchestration and API management. 10 years of experience building scalable API infrastructures for enterprises.', 'default.png', 1, 0),
('judit.m@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Judit', '', 'Móric', 'Marketing Automation Specialist with HubSpot and Marketo expertise. 8 years of experience implementing automation strategies that increase conversions and customer lifetime value.', 'default.png', 1, 0),
('erno@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Ernő', '', 'Fekete', 'WordPress Plugin Developer with 12 years of experience creating high-quality PHP plugins. Strong expertise in WP-CLI and custom post types. Portfolio includes plugins with 100k+ installations.', 'default.png', 1, 0),
('elise@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Elise', '', 'Laurent', 'Illustrator and Digital Artist with expertise in UI illustration and infographics. 7 years of experience creating engaging visual content for digital products and marketing campaigns.', 'default.png', 1, 0),
('karoly@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Károly', '', 'Csonka', 'TypeScript Specialist with expertise in Next.js and modern frontend tooling. 9 years of experience building type-safe applications with excellent developer experience.', 'default.png', 1, 0),
('sylvia.v@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Szilvia', '', 'Villanyák', 'Scrum Master with certification and 10 years of agile transformation experience. Specialized in implementing agile practices and removing blockers in large organizations.', 'default.png', 1, 0),
('viktor.p@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Viktor', '', 'Páll', 'Machine Learning Engineer with expertise in TensorFlow and PyTorch. 10 years of experience building production ML systems for recommendation engines and predictive analytics.', 'default.png', 1, 0),
('magda.s@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Magda', '', 'Szabó', 'Grant Writer specializing in technology and innovation grants. 8 years of experience securing funding for startups and R&D projects. Strong track record of successful applications.', 'default.png', 1, 0),
('sandor.f@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Sándor', '', 'Fülöp', 'Enterprise Architecture Consultant with 12 years of experience designing complex IT landscapes. Specialized in digital transformation strategies for large organizations.', 'default.png', 1, 0),
('zita.m@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Zita', '', 'Madácsi', 'Graphic Logo Designer with award-winning portfolio and 9 years of experience. Specialized in creating memorable brand identities through thoughtful design.', 'default.png', 1, 0),
('peter.v@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Péter', '', 'Vass', 'Ruby on Rails Developer with 11 years of framework expertise and scalable application development. Strong background in rapid MVP development and system architecture.', 'default.png', 1, 0),
('agnieszka.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Agnieszka', '', 'Kuchta', 'IT Compliance Consultant specializing in GDPR and ISO 27001 certifications. 10 years of experience helping organizations achieve and maintain compliance standards.', 'default.png', 1, 0),
('istvan.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'István', '', 'Kulcsár', 'Speech Recognition Systems Developer with expertise in voice AI and NLP. 9 years of experience implementing voice interfaces and conversational AI solutions.', 'default.png', 1, 0),
('veronica@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Veronika', '', 'Sándor', 'Technical Architecture Coach with experience mentoring development teams. 11 years of helping teams improve code quality and system design practices.', 'default.png', 1, 0),
('laszlo.t@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'László', '', 'Takács', 'Go Programming Language Expert with systems programming background. 8 years of experience building high-performance concurrent applications and microservices.', 'default.png', 1, 0),
('katalin.v@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Katalin', '', 'Varga', 'Blockchain Solutions Architect with expertise in Ethereum and enterprise blockchain. 7 years of experience designing and implementing distributed ledger systems.', 'default.png', 1, 0),
('david.l@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Dávid', '', 'Lakatos', 'Augmented Reality Developer specializing in ARKit and ARCore platforms. 8 years of experience creating immersive AR experiences for mobile and web platforms.', 'default.png', 1, 0),
('sandra.m@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Sándor', '', 'Mészáros', 'IoT Application Developer with expertise in sensor networks and embedded systems. 9 years of experience building connected device solutions for smart homes and industrial applications.', 'default.png', 1, 0),
('anna.m@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Anna', '', 'Molnár', 'CRM Solutions Specialist with Salesforce and Dynamics expertise. 10 years of experience implementing CRM systems that improve customer relationships and sales performance.', 'default.png', 1, 0),
('mihaly.s@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Mihály', '', 'Sándor', 'Statistical Analysis Expert with R and Python proficiency. 11 years of experience conducting advanced statistical analysis for research and business intelligence.', 'default.png', 1, 0),
('petra.n@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Petra', '', 'Németh', 'Technical Translation Specialist with software and IT documentation expertise. Bilingual translator with 8 years of experience in technical documentation and localization.', 'default.png', 1, 0),
('george@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'György', '', 'Szabó', 'Game Engine Developer with Unreal Engine expertise. 10 years of experience developing game mechanics and engine optimization for AAA and indie games.', 'default.png', 1, 0),
('barbara.m@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Barbara', '', 'Marosi', 'Batch Processing Systems Architect specializing in large-scale data processing. 9 years of experience designing ETL pipelines and batch jobs for big data environments.', 'default.png', 1, 0),
('tamas.k@gmail.com', '$2b$10$vaifZ47SmZ7K6LKDkXkjEeKB31be4nUmJSmXA1YOjt99EQRaUFBwa', 'Tamás', '', 'Kovács', 'Quantum Computing Researcher exploring quantum algorithms and applications. 7 years of experience working with quantum simulation frameworks and hybrid systems.', 'default.png', 1, 0);



-- Orders Table, Related Tables And Procedures --
CREATE TABLE IF NOT EXISTS `orders`
(
  -- Keys --
  `oid` int(11) NOT NULL, -- Primary key --
  `uid` int(11) NOT NULL, -- Foreign key to users table --
  `freelancer_uid` int(11) NOT NULL DEFAULT -1, -- Foreign key to users table --

  -- Order Details --
  `title` varchar(32) NOT NULL,
  `description` varchar(1024) NOT NULL,
  `type` int(1) NOT NULL COMMENT '1: Website, 2: Desktop App, 3: Mobile App, 4: Other',
  `other_type` varchar(64) DEFAULT NULL, -- Only used if type is 4 (Other) --
  `platform` int(1) NOT NULL COMMENT '1: Windows, 2: Linux, 3: MacOS, 4: Android, 5: IOS', -- Only used for Desktop and Mobile App types --
  `budget` decimal(10,2) NOT NULL,
  `document_url` varchar(255) DEFAULT NULL COMMENT 'Path to the uploaded document',
  `deadline` date NOT NULL,

  -- Project datas --
  `project_version` varchar(32) NOT NULL DEFAULT '1.0.0.',
  `project_url` varchar(255) NULL DEFAULT NULL COMMENT 'Path to the downloadable project',

  -- Status --
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` int(1) NOT NULL DEFAULT '1' COMMENT '1: Pending, 2: In Progress, 3: Completed, 4: Cancelled',

  PRIMARY KEY (`oid`),
  FOREIGN KEY (`uid`) REFERENCES `users`(`uid`) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `orders` (`oid`, `uid`, `freelancer_uid`, `title`, `description`, `type`, `other_type`, `platform`, `budget`, `document_url`, `deadline`, `project_version`, `project_url`, `created_at`, `status`) VALUES
(1, 4, 13, 'E-commerce Platform Development', 'We need a full-featured e-commerce website with product catalog, shopping cart, payment integration (Stripe/PayPal), user accounts, order tracking, and admin dashboard. The platform should support multiple currencies and languages. Requires integration with inventory management system and automated email notifications for order updates.', 1, NULL, NULL, 8500.00, 'ecommerce_requirements.txt', '2026-06-15', '1.0.0', NULL, '2026-03-15 09:30:00', 2),
(2, 5, 15, 'Mobile Fitness Tracking Application', 'Development of a cross-platform mobile app (iOS and Android) for fitness tracking with features including: workout logging, calorie counter, progress analytics, social sharing, community challenges, and integration with wearable devices. App should include push notifications, offline mode, and cloud sync for user data. Design should be modern and intuitive with dark mode support.', 3, NULL, 4, 12000.00, 'fitness_app_specs.txt', '2026-07-30', '1.0.0', NULL, '2026-03-18 14:20:00', 1),
(3, 6, 12, 'Corporate Website Redesign & Modernization', 'Complete redesign of our company website with modern UI/UX principles. Requirements include: responsive design for all devices, SEO optimization, blog integration with CMS, team member portal, client testimonials section, and contact forms with lead management. Must improve page load speed and implement analytics tracking. Current site statistics and branding guidelines will be provided.', 1, NULL, NULL, 6500.00, 'corporate_site_guidelines.txt', '2026-05-20', '2.0.0', NULL, '2026-03-10 11:45:00', 3),
(4, 7, -1, 'Human Resources Management Desktop Application', 'Development of a Windows-based HR management system for managing employee records, attendance tracking, leave requests, payroll integration, performance reviews, and document storage. System should include role-based access control, reporting dashboards, and export functionality. Database design must ensure data security and compliance with labor regulations. User documentation and training materials required.', 2, NULL, 1, 9800.00, 'hr_system_requirements.txt', '2026-08-10', '1.0.0', NULL, '2026-02-28 16:00:00', 2),
(5, 8, 18, 'Online Learning Management System (LMS)', 'Creation of a comprehensive learning platform with course creation tools, student enrollment, video hosting, quiz/assessment features, progress tracking, certificates generation, discussion forums, and instructor analytics. Must support multiple file formats (video, PDF, images). Include email notifications, automated grading, and mobile-responsive design. Budget includes initial content migration from existing platform.', 1, NULL, NULL, 15000.00, 'lms_detailed_specifications.txt', '2026-09-25', '1.0.0', NULL, '2026-03-05 10:15:00', 1),
(6, 24, -1, 'Restaurant Ordering Web Platform', 'We need a complete web platform for our restaurant chain to allow customers to order food online for delivery and pickup. Features should include: dynamic menu management, real-time order status tracking, customer reviews and ratings, loyalty program integration, payment gateway (Stripe/Square), order history, and admin panel for order management. Must be mobile-responsive and support multiple restaurant locations.', 1, NULL, NULL, 11000.00, 'restaurant_platform_specs.txt', '2026-07-10', '1.0.0', NULL, '2026-03-12 13:45:00', 1),
(7, 25, -1, 'Inventory Management System Documentation', 'Comprehensive technical and user documentation for our new inventory management system. Needs to include: system architecture documentation, API reference guide, user manual for different role types (admin, warehouse, manager), troubleshooting guide, and video tutorials. Documentation should be available in both Hungarian and English. Requires professional formatting, diagrams, and screenshots.', 4, 'Technical Documentation Project', NULL, 5500.00, 'inventory_system_overview.txt', '2026-06-01', '1.0.0', NULL, '2026-03-08 10:20:00', 1),
(8, 26, -1, 'Cloud Infrastructure Migration & Setup', 'Migration of our existing on-premises servers to AWS cloud infrastructure. Scope includes: infrastructure assessment, cloud architecture design, database migration, application deployment, security configuration, backup and disaster recovery setup. Need high availability configuration and auto-scaling setup for seasonal traffic spikes. Full documentation and staff training on new cloud environment required.', 4, 'Cloud Migration Project', NULL, 18500.00, 'current_infrastructure_audit.txt', '2026-08-20', '1.0.0', NULL, '2026-03-02 09:00:00', 1),
(9, 27, -1, 'Marketing Website & Blog Platform Redesign', 'Complete redesign of our marketing website with modern aesthetics and improved user engagement. New site should feature: responsive design, integrated blog with SEO optimization, newsletter subscription, testimonials showcase, case studies section, contact forms, and analytics integration. Must include CMS for easy content management by marketing team. Performance optimization for fast loading times critical.', 1, NULL, NULL, 8200.00, 'marketing_site_goals.txt', '2026-06-28', '1.0.0', NULL, '2026-03-14 15:30:00', 1),
(10, 28, -1, 'Mobile App for Project Management', 'Development of a mobile application (iOS and Android) for team project management with features including: project creation and management, task assignment and tracking, team collaboration tools, file attachments, progress reporting, notifications, and offline functionality. Must sync seamlessly with our web-based project management system. Include push notifications and intuitive UI for on-the-go project management.', 3, NULL, 4, 14500.00, 'mobile_pm_requirements.txt', '2026-07-15', '1.0.0', NULL, '2026-03-20 11:15:00', 1),
(11, 44, 94, 'AI-Powered Customer Support Chatbot', 'Development of an intelligent chatbot system with natural language processing capabilities for customer support automation. Must integrate with help desk systems, learn from past interactions, and escalate complex issues to human agents. Features include multi-language support, sentiment analysis, and analytics dashboard. Implementation requires deep ML expertise.', 4, 'AI Chatbot System', NULL, 16000.00, 'chatbot_requirements.txt', '2026-08-10', '1.0.0', NULL, '2026-03-21 10:30:00', 2),
(12, 45, 95, 'Healthcare Patient Portal Web Application', 'Build a HIPAA-compliant patient portal for healthcare providers featuring appointment scheduling, medical records access, prescription management, telemedicine integration, and secure messaging with doctors. System must ensure data security, include multi-factor authentication, and support both web and mobile access with synchronized data.', 1, NULL, NULL, 22000.00, 'healthcare_portal_specs.txt', '2026-09-15', '1.0.0', NULL, '2026-03-19 14:00:00', 1),
(13, 46, 96, 'Supply Chain Visibility Platform', 'Create an enterprise platform for real-time supply chain tracking and management. Features include GPS tracking integration, inventory management, vendor performance analytics, automated alert systems for delays, and predictive analytics for demand forecasting. Dashboard should display KPIs and provide actionable insights for decision makers.', 1, NULL, NULL, 25000.00, 'supply_chain_platform.txt', '2026-10-01', '1.0.0', NULL, '2026-03-18 09:45:00', 2),
(14, 47, 97, 'Educational Video Platform Development', 'Development of a comprehensive video streaming platform for educational content with adaptive bitrate streaming, live class integration, student progress tracking, quiz integration, and certificate generation. Must support HD and 4K video, handle high concurrent viewers, and include creator dashboard for educators.', 1, NULL, NULL, 19500.00, 'edu_video_specs.txt', '2026-09-01', '1.0.0', NULL, '2026-03-22 11:20:00', 1),
(15, 48, 98, 'Real Estate Virtual Tour Platform', 'Build an interactive virtual tour platform for real estate with 360-degree panoramic photos, 3D floor plans, property information integration, and agent booking systems. Include mobile app functionality, lead generation tools, and integration with property management systems. Must be SEO-optimized for search engines.', 1, NULL, NULL, 13000.00, 'realestate_tour_specs.txt', '2026-08-25', '1.0.0', NULL, '2026-03-17 13:15:00', 2),
(16, 49, 99, 'Fintech Mobile Banking Application', 'Develop a cutting-edge mobile banking app with digital wallet, peer-to-peer transfers, bill payments, investment tracking, and fintech API integrations. Security is critical - implement multi-factor authentication, biometric login, and encryption. Must comply with banking regulations and pass security audits.', 3, NULL, 5, 31000.00, 'banking_app_requirements.txt', '2026-10-15', '1.0.0', NULL, '2026-03-16 10:00:00', 2),
(17, 50, 100, 'Social Media Analytics Dashboard', 'Create an advanced analytics platform for monitoring and analyzing social media performance across multiple networks. Features include competitor analysis, audience demographics, engagement metrics, trend prediction, and automated reporting. Build with real-time data processing and support for 50+ social platforms.', 1, NULL, NULL, 17000.00, 'social_analytics_specs.txt', '2026-08-30', '1.0.0', NULL, '2026-03-15 15:30:00', 1),
(18, 51, 101, 'IoT Smart Building Management System', 'Implement a comprehensive IoT platform for building automation including HVAC control, lighting management, security systems, and energy monitoring. System must support thousands of connected devices, provide real-time dashboards, and include predictive maintenance features. Integrate with existing building systems.', 2, NULL, 1, 28000.00, 'iot_building_specs.txt', '2026-09-20', '1.0.0', NULL, '2026-03-14 12:45:00', 1),
(19, 52, 102, 'E-Learning Content Management System', 'Develop a sophisticated LMS with advanced course management, student progress analytics, interactive assessments, and adaptive learning paths. Include instructor tools for content creation, student communication, and performance tracking. Support offline learning and mobile accessibility.', 1, NULL, NULL, 20000.00, 'lms_advanced_specs.txt', '2026-09-10', '1.0.0', NULL, '2026-03-13 08:20:00', 2),
(20, 53, 103, 'Blockchain-Based Supply Chain Verification', 'Create a blockchain solution for supply chain verification and product authentication. Features include immutable record-keeping, smart contracts for automated verification, QR code integration for consumers, and real-time tracking. Must ensure transparency, prevent counterfeiting, and provide audit trails.', 4, 'Blockchain Supply Chain', NULL, 35000.00, 'blockchain_specs.txt', '2026-10-30', '1.0.0', NULL, '2026-03-12 14:10:00', 1),
(21, 54, 104, 'AI-Powered Job Matching Platform', 'Build a recruitment platform using machine learning for intelligent job-candidate matching. Include resume parsing, skill assessment, video interview analysis, and predictive hiring analytics. Provide talent insights and create data-driven recruitment strategies for HR teams.', 1, NULL, NULL, 18500.00, 'recruitment_ai_specs.txt', '2026-08-15', '1.0.0', NULL, '2026-03-11 09:30:00', 2),
(22, 55, 105, 'Augmented Reality Furniture Placement App', 'Develop an AR mobile application allowing users to visualize furniture in their space before purchase. Include 3D model library integration, real-time visualization with device camera, purchase directly from app, and AR-based interior design recommendations.', 3, NULL, 4, 16500.00, 'ar_furniture_specs.txt', '2026-08-20', '1.0.0', NULL, '2026-03-10 11:00:00', 1),
(23, 56, 106, 'Professional Networking Platform', 'Create a LinkedIn-like platform for professional networking with features like profile building, connection management, job listings, content sharing, messaging, and recommendation systems. Include notifications, search functionality, and analytics for Premium users.', 1, NULL, NULL, 24000.00, 'networking_platform_specs.txt', '2026-09-25', '1.0.0', NULL, '2026-03-09 16:45:00', 2),
(24, 57, 107, 'Video Conferencing System Development', 'Build an enterprise video conferencing platform with HD video, screen sharing, recording capabilities, chat integration, virtual backgrounds, and meeting scheduling. Include security features like end-to-end encryption and meeting passwords. Support up to 1000 concurrent participants.', 1, NULL, NULL, 26000.00, 'video_conference_specs.txt', '2026-10-05', '1.0.0', NULL, '2026-03-08 13:20:00', 1),
(25, 58, 108, 'Subscription Management Platform', 'Develop a comprehensive subscription billing system supporting multiple payment methods, automated invoicing, dunning management, usage-based billing, and churn prediction. Include customer portal, revenue analytics, and integration with accounting systems.', 1, NULL, NULL, 15000.00, 'subscription_platform_specs.txt', '2026-08-18', '1.0.0', NULL, '2026-03-07 10:15:00', 2),
(26, 59, 109, 'Geolocation-Based Service Discovery App', 'Create a mobile app for discovering nearby services (restaurants, shops, services) with reviews, ratings, real-time availability, reservation systems, and loyalty programs. Include GPS integration, location-based notifications, and integration with payment gateways.', 3, NULL, 4, 13500.00, 'service_discovery_specs.txt', '2026-08-05', '1.0.0', NULL, '2026-03-06 14:30:00', 1),
(27, 60, 110, 'Fleet Management and Tracking System', 'Develop a fleet management platform with real-time GPS tracking, route optimization, fuel consumption monitoring, maintenance scheduling, and driver behavior analytics. Include mobile app for drivers and web dashboard for fleet managers with reporting capabilities.', 1, NULL, NULL, 21000.00, 'fleet_management_specs.txt', '2026-09-12', '1.0.0', NULL, '2026-03-05 09:00:00', 2),
(28, 61, 111, 'Digital Rights Management Platform', 'Build a DRM solution for content creators protecting digital assets with watermarking, encryption, usage restrictions, and licensing management. Include APIs for third-party integration, analytics dashboard, and enforcement mechanisms for unauthorized access prevention.', 1, NULL, NULL, 19000.00, 'drm_platform_specs.txt', '2026-09-05', '1.0.0', NULL, '2026-03-04 11:45:00', 1),
(29, 62, 112, 'Progressive Web App for Food Delivery', 'Develop a PWA for food delivery with offline functionality, push notifications, real-time order tracking, integrated payments, and restaurant management backend. Must work seamlessly on all devices with minimal data usage for emerging markets.', 1, NULL, NULL, 17000.00, 'food_delivery_pwa_specs.txt', '2026-08-22', '1.0.0', NULL, '2026-03-03 15:25:00', 2),
(30, 63, 113, 'Predictive Maintenance AI System', 'Create an AI system for industrial equipment predictive maintenance using machine learning on IoT sensor data. System should predict failures, recommend maintenance schedules, reduce downtime, and optimize maintenance costs. Include dashboard for maintenance teams and integration with CMMS systems.', 4, 'Predictive Maintenance AI', NULL, 32000.00, 'predictive_maintenance_specs.txt', '2026-10-10', '1.0.0', NULL, '2026-03-02 12:30:00', 2),
(31, 64, -1, 'Multi-Vendor Marketplace Platform', 'Build a comprehensive e-commerce marketplace supporting multiple vendors with separate stores, inventory management, commission systems, dispute resolution, and vendor analytics. Include secure payment processing, quality assurance tools, and customer review systems.', 1, NULL, NULL, 27000.00, 'marketplace_specs.txt', '2026-09-30', '1.0.0', NULL, '2026-03-01 14:00:00', 1),
(32, 65, -1, 'Event Management and Ticketing System', 'Develop a full event management platform with ticketing, attendee management, seat selection, QR code verification, and post-event analytics. Include payment processing, email notifications, and integration with venue management systems.', 1, NULL, NULL, 16000.00, 'event_ticketing_specs.txt', '2026-08-28', '1.0.0', NULL, '2026-02-28 10:20:00', 1),
(33, 66, -1, 'Document Management and Workflow System', 'Create an enterprise document management system with version control, workflow automation, approval routing, compliance tracking, and full-text search. Include integration with existing systems, audit trails, and digital signature support.', 1, NULL, NULL, 19500.00, 'document_management_specs.txt', '2026-09-08', '1.0.0', NULL, '2026-02-27 13:45:00', 1),
(34, 67, -1, 'Energy Consumption Optimization Platform', 'Build a platform for analyzing and optimizing energy consumption with real-time monitoring, predictive analytics for peak usage, recommendations for energy savings, and carbon footprint tracking. Include API integrations with smart meters.', 1, NULL, NULL, 15000.00, 'energy_optimization_specs.txt', '2026-08-12', '1.0.0', NULL, '2026-02-26 09:30:00', 1),
(35, 68, -1, 'Mental Health Support Application', 'Develop a mental health and wellness application with meditation guides, therapist directory, appointment scheduling, mood tracking, and crisis support resources. Ensure privacy, HIPAA compliance, and integration with professional mental health services.', 1, NULL, NULL, 18000.00, 'mental_health_app_specs.txt', '2026-09-03', '1.0.0', NULL, '2026-02-25 11:15:00', 1),
(36, 69, -1, 'Inventory Forecasting AI System', 'Create an AI-powered inventory management system that predicts demand, optimizes stock levels, identifies slow-moving items, and suggests reorder points. Use historical data and market trends for accurate forecasting to reduce waste and stockouts.', 1, NULL, NULL, 17500.00, 'inventory_ai_specs.txt', '2026-08-20', '1.0.0', NULL, '2026-02-24 14:50:00', 1),
(37, 70, -1, 'Travel Planning Recommendation Engine', 'Build an intelligent travel planning platform using ML to recommend destinations, accommodations, and activities based on user preferences, budget, and past travel history. Include price comparison, booking integration, and itinerary management.', 1, NULL, NULL, 16500.00, 'travel_engine_specs.txt', '2026-08-25', '1.0.0', NULL, '2026-02-23 10:00:00', 1),
(38, 71, -1, 'Custom API Development Framework', 'Develop reusable API framework and middleware components for rapid API development with built-in security, rate limiting, caching, and monitoring. Create comprehensive documentation and developer portal for third-party integrations.', 4, 'API Framework Project', NULL, 14000.00, 'api_framework_specs.txt', '2026-08-15', '1.0.0', NULL, '2026-02-22 15:30:00', 1),
(39, 72, -1, 'Quality Automation Testing Suite', 'Create a comprehensive automated testing platform with test case management, CI/CD integration, cross-browser testing, performance testing, and detailed reporting. Support multiple programming languages and frameworks with easy integration.', 1, NULL, NULL, 13500.00, 'qa_automation_specs.txt', '2026-08-10', '1.0.0', NULL, '2026-02-21 12:10:00', 1),
(40, 73, -1, 'Data Visualization Analytics Engine', 'Build a powerful data visualization platform supporting multiple chart types, real-time data streaming, drill-down capabilities, custom dashboards, and scheduled report generation. Include data source integration and export functionalities.', 1, NULL, NULL, 15500.00, 'data_viz_specs.txt', '2026-08-18', '1.0.0', NULL, '2026-02-20 09:45:00', 1);



-- Order messages table --
CREATE TABLE IF NOT EXISTS `order_messages`
(
  -- Keys --
  `mid` int(11) NOT NULL AUTO_INCREMENT, -- Primary Key --
  `oid` int(11) NOT NULL, -- Foreign Key to orders table --
  `uid` int(11) NOT NULL, -- Foreign Key to users table --

  -- Message Details --
  `message` varchar(1024) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`mid`),
  FOREIGN KEY (`oid`) REFERENCES `orders`(`oid`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`uid`) REFERENCES `users`(`uid`) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `order_messages` (`oid`, `uid`, `message`, `created_at`) VALUES
(1, 4, 'Hello, I have some questions about the e-commerce platform requirements. Specifically, what payment gateways do you plan to integrate?', '2026-03-16 10:00:00'),
(1, 13, 'Hi! We can integrate Stripe and PayPal as mentioned in the requirements. Do you have any preference?', '2026-03-16 11:00:00'),
(1, 4, 'Stripe would be great. Also, about the inventory management, how will it sync with our existing system?', '2026-03-16 12:00:00'),
(1, 13, 'We\'ll use APIs to sync with your inventory system. I\'ll need the API documentation from you.', '2026-03-16 13:00:00'),
(1, 4, 'Perfect, I\'ll send that over. When can we schedule a kickoff meeting?', '2026-03-16 14:00:00'),
(1, 13, 'How about next Tuesday at 2 PM?', '2026-03-16 15:00:00'),
(2, 5, 'Hi, I\'m excited about the fitness app project. Do you have experience with wearable integrations?', '2026-03-19 10:00:00'),
(2, 15, 'Yes, I\'ve worked with Fitbit and Apple Health APIs before. What wearables do you want to support?', '2026-03-19 11:00:00'),
(2, 5, 'Primarily Fitbit and Apple Watch. Also, about the UI design, I have some mockups ready.', '2026-03-19 12:00:00'),
(2, 15, 'Great, can you share them? I\'ll review and provide feedback.', '2026-03-19 13:00:00'),
(2, 5, 'Sure, sending now. Let\'s discuss the color scheme.', '2026-03-19 14:00:00'),
(2, 15, 'The mockups look good. I suggest a vibrant color palette for motivation.', '2026-03-19 15:00:00'),
(3, 6, 'Hello, for the website redesign, we need SEO optimization. What tools do you use?', '2026-03-11 10:00:00'),
(3, 12, 'I use Google Analytics and SEMrush for SEO. What are your current SEO goals?', '2026-03-11 11:00:00'),
(3, 6, 'Improve organic traffic by 30%. Also, integrate a blog.', '2026-03-11 12:00:00'),
(3, 12, 'Understood. I\'ll include that in the proposal.', '2026-03-11 13:00:00'),
(3, 6, 'Good. When can you start?', '2026-03-11 14:00:00'),
(3, 12, 'As soon as you approve the wireframes.', '2026-03-11 15:00:00'),
(5, 8, 'Hi, for the LMS project, what video hosting solution do you recommend?', '2026-03-06 10:00:00'),
(5, 18, 'I recommend using AWS S3 with CloudFront for scalable video hosting. It handles high traffic well.', '2026-03-06 11:00:00'),
(5, 8, 'That sounds good. How about quiz integration?', '2026-03-06 12:00:00'),
(5, 18, 'We can integrate quizzes with automated grading. What types of assessments do you need?', '2026-03-06 13:00:00'),
(5, 8, 'Multiple choice and essay questions. Also, progress tracking.', '2026-03-06 14:00:00'),
(5, 18, 'Got it. I\'ll design the system accordingly.', '2026-03-06 15:00:00'),
(11, 44, 'Hello, for the AI chatbot, what NLP technologies will you use?', '2026-03-22 10:00:00'),
(11, 94, 'We\'ll use Google Dialogflow or Microsoft Bot Framework for NLP. Which do you prefer?', '2026-03-22 11:00:00'),
(11, 44, 'Dialogflow is fine. How about multi-language support?', '2026-03-22 12:00:00'),
(11, 94, 'Dialogflow supports multiple languages. We can add Hungarian and English.', '2026-03-22 13:00:00'),
(11, 44, 'Perfect. What about escalation to human agents?', '2026-03-22 14:00:00'),
(11, 94, 'We\'ll implement sentiment analysis to detect when to escalate.', '2026-03-22 15:00:00'),
(12, 45, 'Hi, for the healthcare portal, HIPAA compliance is crucial. How will you ensure it?', '2026-03-20 10:00:00'),
(12, 95, 'We\'ll use encryption, secure authentication, and regular security audits. All data will be encrypted at rest and in transit.', '2026-03-20 11:00:00'),
(12, 45, 'Good. What telemedicine features will be included?', '2026-03-20 12:00:00'),
(12, 95, 'Video calls, appointment scheduling, and secure messaging with doctors.', '2026-03-20 13:00:00'),
(12, 45, 'Excellent. When can we review the security protocols?', '2026-03-20 14:00:00'),
(12, 95, 'Next week. I\'ll prepare the documentation.', '2026-03-20 15:00:00'),
(13, 46, 'Hello, for the supply chain platform, what real-time tracking features will you implement?', '2026-03-19 10:00:00'),
(13, 96, 'GPS tracking, ETA predictions, and automated alerts for delays. Integration with IoT sensors.', '2026-03-19 11:00:00'),
(13, 46, 'Great. How about vendor performance analytics?', '2026-03-19 12:00:00'),
(13, 96, 'Dashboards with KPIs, delivery times, and quality metrics.', '2026-03-19 13:00:00'),
(13, 46, 'Perfect. What data sources will you need?', '2026-03-19 14:00:00'),
(13, 96, 'Shipment data, vendor information, and historical performance.', '2026-03-19 15:00:00'),
(14, 47, 'Hi, for the educational video platform, what adaptive bitrate streaming will you use?', '2026-03-23 10:00:00'),
(14, 97, 'We\'ll use HLS or DASH for adaptive streaming. Supports HD and 4K.', '2026-03-23 11:00:00'),
(14, 47, 'Good. How about live class integration?', '2026-03-23 12:00:00'),
(14, 97, 'Real-time streaming with chat and Q&A features.', '2026-03-23 13:00:00'),
(14, 47, 'Excellent. What about certificate generation?', '2026-03-23 14:00:00'),
(14, 97, 'Automated certificates upon course completion.', '2026-03-23 15:00:00'),
(15, 48, 'Hello, for the virtual tour platform, what 3D technologies will you use?', '2026-03-18 10:00:00'),
(15, 98, 'Three.js or Babylon.js for 3D rendering. Supports panoramic photos and floor plans.', '2026-03-18 11:00:00'),
(15, 48, 'Great. How about agent booking integration?', '2026-03-18 12:00:00'),
(15, 98, 'Direct booking forms with calendar integration.', '2026-03-18 13:00:00'),
(15, 48, 'Perfect. What SEO features?', '2026-03-18 14:00:00'),
(15, 98, 'Meta tags, sitemaps, and structured data for properties.', '2026-03-18 15:00:00'),
(16, 49, 'Hi, for the banking app, security is paramount. What measures will you implement?', '2026-03-17 10:00:00'),
(16, 99, 'Biometric authentication, end-to-end encryption, and regular penetration testing.', '2026-03-17 11:00:00'),
(16, 49, 'Good. What fintech APIs will be integrated?', '2026-03-17 12:00:00'),
(16, 99, 'Payment APIs, investment platforms, and budgeting tools.', '2026-03-17 13:00:00'),
(16, 49, 'Excellent. When can we discuss compliance?', '2026-03-17 14:00:00'),
(16, 99, 'Next Monday. I\'ll prepare the compliance checklist.', '2026-03-17 15:00:00'),
(17, 50, 'Hello, for the social analytics dashboard, what social platforms will you support?', '2026-03-16 10:00:00'),
(17, 100, 'Facebook, Twitter, Instagram, LinkedIn, and TikTok initially.', '2026-03-16 11:00:00'),
(17, 50, 'Great. How about real-time data processing?', '2026-03-16 12:00:00'),
(17, 100, 'Using streaming APIs and real-time databases.', '2026-03-16 13:00:00'),
(17, 50, 'Perfect. What reporting features?', '2026-03-16 14:00:00'),
(17, 100, 'Automated reports, custom dashboards, and trend analysis.', '2026-03-16 15:00:00'),
(18, 51, 'Hi, for the IoT building system, what protocols will you use?', '2026-03-15 10:00:00'),
(18, 101, 'MQTT and CoAP for IoT communication. Supports thousands of devices.', '2026-03-15 11:00:00'),
(18, 51, 'Good. How about predictive maintenance?', '2026-03-15 12:00:00'),
(18, 101, 'Machine learning algorithms to predict failures.', '2026-03-15 13:00:00'),
(18, 51, 'Excellent. What integration with existing systems?', '2026-03-15 14:00:00'),
(18, 101, 'APIs for HVAC, lighting, and security systems.', '2026-03-15 15:00:00'),
(19, 52, 'Hello, for the LMS, what adaptive learning features will you include?', '2026-03-14 10:00:00'),
(19, 102, 'Personalized learning paths based on student performance.', '2026-03-14 11:00:00'),
(19, 52, 'Great. How about offline learning?', '2026-03-14 12:00:00'),
(19, 102, 'Progressive Web App with offline capabilities.', '2026-03-14 13:00:00'),
(19, 52, 'Perfect. What assessment types?', '2026-03-14 14:00:00'),
(19, 102, 'Quizzes, assignments, and peer reviews.', '2026-03-14 15:00:00'),
(20, 53, 'Hi, for the blockchain supply chain, what consensus mechanism?', '2026-03-13 10:00:00'),
(20, 103, 'Proof of Work or Proof of Stake, depending on requirements.', '2026-03-13 11:00:00'),
(20, 53, 'Good. How about QR code integration?', '2026-03-13 12:00:00'),
(20, 103, 'For product verification and consumer tracking.', '2026-03-13 13:00:00'),
(20, 53, 'Excellent. What audit trails?', '2026-03-13 14:00:00'),
(20, 103, 'Immutable records of all transactions.', '2026-03-13 15:00:00'),
(21, 54, 'Hello, for the job matching platform, what ML algorithms?', '2026-03-12 10:00:00'),
(21, 104, 'Collaborative filtering and natural language processing.', '2026-03-12 11:00:00'),
(21, 54, 'Great. How about video interviews?', '2026-03-12 12:00:00'),
(21, 104, 'Integrated video platform with analysis.', '2026-03-12 13:00:00'),
(21, 54, 'Perfect. What data privacy measures?', '2026-03-12 14:00:00'),
(21, 104, 'GDPR compliance and data anonymization.', '2026-03-12 15:00:00'),
(22, 55, 'Hi, for the AR furniture app, what AR frameworks?', '2026-03-11 10:00:00'),
(22, 105, 'ARKit for iOS and ARCore for Android.', '2026-03-11 11:00:00'),
(22, 55, 'Good. How about 3D model library?', '2026-03-11 12:00:00'),
(22, 105, 'Integration with furniture manufacturer APIs.', '2026-03-11 13:00:00'),
(22, 55, 'Excellent. What purchase integration?', '2026-03-11 14:00:00'),
(22, 105, 'Direct checkout with payment gateways.', '2026-03-11 15:00:00'),
(23, 56, 'Hello, for the networking platform, what features like LinkedIn?', '2026-03-10 10:00:00'),
(23, 106, 'Profiles, connections, messaging, and content sharing.', '2026-03-10 11:00:00'),
(23, 56, 'Great. How about job listings?', '2026-03-10 12:00:00'),
(23, 106, 'Advanced search and application tracking.', '2026-03-10 13:00:00'),
(23, 56, 'Perfect. What analytics for Premium?', '2026-03-10 14:00:00'),
(23, 106, 'Profile views, connection insights, and engagement metrics.', '2026-03-10 15:00:00'),
(24, 57, 'Hi, for the video conferencing, what security features?', '2026-03-09 10:00:00'),
(24, 107, 'End-to-end encryption and meeting passwords.', '2026-03-09 11:00:00'),
(24, 57, 'Good. How about screen sharing?', '2026-03-09 12:00:00'),
(24, 107, 'HD screen sharing with annotation tools.', '2026-03-09 13:00:00'),
(24, 57, 'Excellent. What recording capabilities?', '2026-03-09 14:00:00'),
(24, 107, 'Cloud-based recording with automatic transcription.', '2026-03-09 15:00:00'),
(25, 58, 'Hello, for the subscription platform, what billing cycles?', '2026-03-08 10:00:00'),
(25, 108, 'Monthly, quarterly, and annual with proration.', '2026-03-08 11:00:00'),
(25, 58, 'Great. How about churn prediction?', '2026-03-08 12:00:00'),
(25, 108, 'ML models analyzing usage patterns.', '2026-03-08 13:00:00'),
(25, 58, 'Perfect. What payment methods?', '2026-03-08 14:00:00'),
(25, 108, 'Credit cards, PayPal, and bank transfers.', '2026-03-08 15:00:00'),
(26, 59, 'Hi, for the service discovery app, what location services?', '2026-03-07 10:00:00'),
(26, 109, 'GPS and geofencing for nearby services.', '2026-03-07 11:00:00'),
(26, 59, 'Good. How about loyalty programs?', '2026-03-07 12:00:00'),
(26, 109, 'Points system with rewards and discounts.', '2026-03-07 13:00:00'),
(26, 59, 'Excellent. What review system?', '2026-03-07 14:00:00'),
(26, 109, 'Star ratings and detailed reviews.', '2026-03-07 15:00:00'),
(27, 60, 'Hello, for the fleet management, what GPS accuracy?', '2026-03-06 10:00:00'),
(27, 110, 'Real-time GPS with 5-meter accuracy.', '2026-03-06 11:00:00'),
(27, 60, 'Great. How about driver behavior?', '2026-03-06 12:00:00'),
(27, 110, 'Monitoring speed, braking, and fuel efficiency.', '2026-03-06 13:00:00'),
(27, 60, 'Perfect. What reporting?', '2026-03-06 14:00:00'),
(27, 110, 'Daily and weekly reports with analytics.', '2026-03-06 15:00:00'),
(28, 61, 'Hi, for the DRM platform, what encryption methods?', '2026-03-05 10:00:00'),
(28, 111, 'AES-256 encryption with digital watermarks.', '2026-03-05 11:00:00'),
(28, 61, 'Good. How about usage restrictions?', '2026-03-05 12:00:00'),
(28, 111, 'Time-limited access and device restrictions.', '2026-03-05 13:00:00'),
(28, 61, 'Excellent. What API integrations?', '2026-03-05 14:00:00'),
(28, 111, 'For content management and distribution.', '2026-03-05 15:00:00'),
(29, 62, 'Hello, for the PWA food delivery, what offline features?', '2026-03-04 10:00:00'),
(29, 112, 'Order history and basic browsing offline.', '2026-03-04 11:00:00'),
(29, 62, 'Great. How about push notifications?', '2026-03-04 12:00:00'),
(29, 112, 'Order status and promotional notifications.', '2026-03-04 13:00:00'),
(29, 62, 'Perfect. What payment integration?', '2026-03-04 14:00:00'),
(29, 112, 'Stripe and PayPal with saved cards.', '2026-03-04 15:00:00'),
(30, 63, 'Hi, for the predictive maintenance, what IoT sensors?', '2026-03-03 10:00:00'),
(30, 113, 'Vibration, temperature, and pressure sensors.', '2026-03-03 11:00:00'),
(30, 63, 'Good. How about ML models?', '2026-03-03 12:00:00'),
(30, 113, 'Time series analysis and anomaly detection.', '2026-03-03 13:00:00'),
(30, 63, 'Excellent. What dashboard features?', '2026-03-03 14:00:00'),
(30, 113, 'Real-time alerts and maintenance recommendations.', '2026-03-03 15:00:00');



COMMIT;